# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Id', models.CharField(max_length=10)),
                ('Dep_Id', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Qualification', models.CharField(max_length=50)),
                ('Gender', models.CharField(default='Male', max_length=10)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
